### PR TITLE
fix: handle PgDataType.voidType

### LINKED ISSUE #125: Unimplemented Text Decoding Types in `PostgresTextDecoder`
I think at some point we need to implement the rest of the types here:

https://github.com/isoos/postgresql-dart/blob/18b22c5ec9d1788960424d97223faa1a7f608e22/lib/src/text_codec.dart#L221-L254

Also:
I caught this incorrect decoding by coincidence when testing. Like in `psql`, in text data format (such in the simple protocol), `true` and `false` are returned as `t` and `f`, respectively. 
https://github.com/isoos/postgresql-dart/blob/18b22c5ec9d1788960424d97223faa1a7f608e22/lib/src/text_codec.dart#L245-L246

Though, I am not sure if other valid boolean representation are possible (e.g. for `true`: `1`, `y`, `yes`, `on`.. etc) to appear here.  

I will push a small fix for this one in https://github.com/isoos/postgresql-dart/pull/118

### PR DESCRIPTION
**Pull request by osaxma**
Partly fixes #125

- For `PgDataType.voidType`, return `null`. 
- For any unimplemented type, return whatever was decoded as text 
  -  I believe it's better to return something than throw an exception 

----
Context:

I was running this query and I received the following error:

```
--> data ReadyForQueryMessage(state = I)
<-- data Instance of 'QueryMessage'
      sending Qnselect pg_drop_replication_slot('a_test_slot') from pg_replication_slots where slot_name = 'a_test_slot';
--> data Instance of 'RowDescriptionMessage'
--> data Data Row Message: [[]]
Unhandled exception:
UnimplementedError: Text decoding for PgDataType.voidType
```

### CODE REVIEW

File: lib/src/text_codec.dart [hunk 1]
```diff
@@ -248,11 +248,16 @@ class PostgresTextDecoder<T extends Object> {
...
+      case PgDataType.voidType:
+        // TODO: is returning `null` here is the appripriate thing to do? 
+        return null;
 
       // We could list out all cases, but it's about 20 lines of code.
+      // TODO: implement the rest of the types 
       // ignore: no_default_cases
       default:
-        throw UnimplementedError('Text decoding for $_dataType');
+        return asText as T;
```
Comment (isoos) [inline lib/src/text_codec.dart:260]: Maybe?
```
if (asText is T) return asText;
throw UnimplementedError('Text decoding for $_dataType');
```

Comment (osaxma) [reply lib/src/text_codec.dart]:
```dart
        if (asText is T) {
          return asText as T; // i had to do it like this; otherwise it gives an error 
        }
        throw UnimplementedError('Text decoding for $_dataType');
```

**Comment by isoos** [comment]
thanks!
